In [5]:
import pandas as pd

In [6]:
# df = pd.read_csv(r"C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/cleaned_dataset.csv")
pd.set_option('display.max_columns', None)

In [145]:
df.head(2)

,iyear,imonth,iday,country,country_txt,region,region_txt,provstate,city,latitude,longitude,attacktype1_txt,attacktype2_txt,attacktype3_txt,weaptype1_txt,weapsubtype1_txt,weaptype2_txt,weapsubtype2_txt,weaptype3_txt,weapsubtype3_txt,weaptype4_txt,weapsubtype4_txt,targtype1_txt,targsubtype1_txt,targtype2_txt,targsubtype2_txt,targtype3_txt,targsubtype3_txt,gname,gname2,gname3,motive,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,propcomment,summary,suicide,multiple
0,1970,7,2,58,Dominican Republic,2,Central America & Caribbean,Unknown,Santo Domingo,18.456792,-69.951164,Assassination,Armed Assault,Facility/Infrastructure Attack,Unknown,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Private Citizens & Property,Named Civilian,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,MANO-D,Unknown,Unknown,Unknown,1.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
1,1970,0,0,130,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),Armed Assault,Facility/Infrastructure Attack,Unknown,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,23rd of September Communist League,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0

In [146]:
df.shape
df["imonth"].unique()

array([ 7,  0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12], dtype=int64)

In [48]:




# Create a dictionary to map numeric values to month names
month_map = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun",
    7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

# Replace numeric month values with month names
df['imonth'] = df['imonth'].map(month_map)

# If there are any missing or zero values, you can handle them like this:
df['imonth'] = df['imonth'].fillna('Unknown')  # Replace NaN with 'Unknown'
df['imonth'] = df['imonth'].replace(0, 'Unknown')  # Replace 0 with 'Unknown'

# Print the updated DataFrame to verify the changes
print(df[['iyear', 'imonth', 'iday']].head())

   iyear   imonth  iday
0   1970      Jul     2
1   1970  Unknown     0
2   1970      Jan     0
3   1970      Jan     0
4   1970      Jan     0

In [50]:
df["imonth"].value_counts()

May        16875
Jul        16268
Aug        15800
Oct        15563
Jun        15359
Mar        15257
Apr        15152
Jan        14936
Nov        14906
Sep        14180
Feb        13879
Dec        13496
Unknown       20
Name: imonth, dtype: int64

In [51]:
df

,iyear,imonth,iday,country,country_txt,region,region_txt,provstate,city,latitude,longitude,attacktype1_txt,attacktype2_txt,attacktype3_txt,weaptype1_txt,weapsubtype1_txt,weaptype2_txt,weapsubtype2_txt,weaptype3_txt,weapsubtype3_txt,weaptype4_txt,weapsubtype4_txt,targtype1_txt,targsubtype1_txt,targtype2_txt,targsubtype2_txt,targtype3_txt,targsubtype3_txt,gname,gname2,gname3,motive,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,propcomment,summary,suicide,multiple
0,1970,Jul,2,Dominican Republic,Dominican Republic,2,Central America & Caribbean,Unknown,Santo Domingo,18.456792,-69.951164,Assassination,Armed Assault,Facility/Infrastructure Attack,Unknown,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Private Citizens & Property,Named Civilian,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,MANO-D,Unknown,Unknown,Unknown,1.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
1,1970,Unknown,0,Mexico,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),Armed Assault,Facility/Infrastructure Attack,Unknown,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,23rd of September Communist League,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
2,1970,Jan,0,Philippines,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,Assassination,Armed Assault,Facility/Infrastructure Attack,Unknown,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Journalists & Media,Radio Journalist/Staff/Facility,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Unknown,Unknown,Unknown,Unknown,1.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
3,1970,Jan,0,Greece,Greece,8,Western Europe,Attica,Athens,37.997490,23.762728,Bombing/Explosion,Armed Assault,Facility/Infrastructure Attack,Explosives,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Government (Diplomatic),Embassy/Consulate,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Unknown,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,1,Unknown,0.0,Unknown,Unknown,0,0.0
4,1970,Jan,0,Japan,Japan,4,East Asia,Fukouka,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,Armed Assault,Facility/Infrastructure Attack,Incendiary,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Government (Diplomatic),Embassy/Consulate,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Unknown,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,1,Unknown,0.0,Unknown,Unknown,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017,Dec,31,Somalia,Somalia,11,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,2.359673,45.385034,Armed Assault,Armed Assault,Facility/Infrastructure Attack,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Military,Military Checkpoint,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Al-Shabaab,Unknown,Unknown,Unknown,1.0,0.0,0.0,2.0,0.0,0.0,-9,Unknown,0.0,Unknown,12/31/2017: Assailants opened fire on a Somali...,0,0.0
181687,2017,Dec,31,Syria,Syria,10,Middle East & North Africa,Lattakia,Jableh,35.407278,35.942679,Bombing/Explosion,Armed Assault,Facility/Infrastructure Attack,Explosives,"Projectile (rockets, mortars, RPGs, etc.)",Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Military,Military Barracks/Base/Headquarters/Checkpost,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Muslim extremists,Unknown,Unknown,Unknown,2.0,0.0,0.0,7.0,0.0,0.0,1,4.0,-99.0,Seven military planes were damaged in this att...,12/31/2017: Assailants launched mortars at the...,0,0.0
181688,2017,Dec,31,Philippines,Philippines,5,Southeast Asia,Maguindanao,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,Armed Assault,Facility/Infrastructure Attack,Incendiary,Arson/Fire,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Private Citizens & Property,House/Apartment/Residence,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Bangsamoro Islamic Freedom Movement (BIFM),Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,1,4.0,-99.0,Houses were damaged in this attack.,12/31/2017: Assailants set fire to houses in K...,0,0.0
181689,2017,Dec,31,India,India,6,South Asia,Manipur,Imphal,24.798346,93.940430,Bombing/Explosion,Armed Assault,Facility/Infrastructure Attack,Explosives,Grenade,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Government (General),Government Building/Facility/Office,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Unknown,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,-9,Unknown,0.0,Unknown,12/31/2017: Assailants threw a grenade at a Fo...,0,0.0
181690,2017,Dec,31,Philippines,Philippines,5,Southeast Asia,Maguindanao,Cotabato City,7.209594,124.241966,Bombing/Explosion,Armed Assault,Facility/Infrastructure Attack,Explosives,Unknown Explosive Type,Firearms,Unknown Gun Type,Firearms,Unknown Gun Type,Firearms,Automatic or Semi-Automatic Rifle,Unknown,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Unknown,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,12/31/2017: An explosive device was discovered...,0,0.0

In [147]:
df.shape

(181691, 45)

In [53]:
df["country"].value_counts()

Iraq                   24636
Pakistan               14368
Afghanistan            12731
India                  11960
Colombia                8306
                       ...
International              1
Wallis and Futuna          1
South Vietnam              1
Andorra                    1
Antigua and Barbuda        1
Name: country, Length: 205, dtype: int64

In [54]:
df.to_csv(r"C:\Users\ujjwa\OneDrive\Desktop\DBDA-PROJECT\clean_dataset.csv", index=False)

In [7]:
df1 = pd.read_csv(r"C:\Users\ujjwa\OneDrive\Desktop\DBDA-PROJECT\clean_dataset.csv")

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_26740\1240924890.py:1: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(r"C:\Users\ujjwa\OneDrive\Desktop\DBDA-PROJECT\clean_dataset.csv")

In [8]:
df1.shape

(181691, 45)

In [9]:
df1.columns

Index(['iyear', 'imonth', 'iday', 'country', 'country_txt', 'region',
       'region_txt', 'provstate', 'city', 'latitude', 'longitude',
       'attacktype1_txt', 'attacktype2_txt', 'attacktype3_txt',
       'weaptype1_txt', 'weapsubtype1_txt', 'weaptype2_txt',
       'weapsubtype2_txt', 'weaptype3_txt', 'weapsubtype3_txt',
       'weaptype4_txt', 'weapsubtype4_txt', 'targtype1_txt',
       'targsubtype1_txt', 'targtype2_txt', 'targsubtype2_txt',
       'targtype3_txt', 'targsubtype3_txt', 'gname', 'gname2', 'gname3',
       'motive', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus',
       'nwoundte', 'property', 'propextent', 'propvalue', 'propcomment',
       'summary', 'suicide', 'multiple'],
      dtype='object')

In [10]:
df1 = df1.drop(["country","region","attacktype2_txt","attacktype3_txt","weaptype2_txt","weapsubtype2_txt",
               "weaptype2_txt","weapsubtype2_txt","weaptype3_txt","weapsubtype3_txt",
               "weaptype4_txt","weapsubtype4_txt"],axis=1)

In [11]:
df1.head(2)
df1.shape

(181691, 35)

In [12]:
df1 = df1.rename(columns={"iyear":"year","imonth":"month","country_txt":"country","region_txt":"region",
                       "attacktype1_txt":"attacktype","weaptype1_txt":"weaptype","weapsubtype1_txt":"weapsubtype",
                      "targtype1_txt":"targtype","targsubtype1_txt":"targsubtype","gname":"group_name"})

In [13]:
df1.head(4)
import numpy as np

In [17]:
# cc= np.intersect1d(df.columns,df1.columns)
# print(cc)
df1.head(2)

,year,month,iday,country,region,provstate,city,latitude,longitude,attacktype,weaptype,weapsubtype,targtype,targsubtype,targtype2_txt,targsubtype2_txt,targtype3_txt,targsubtype3_txt,group_name,gname2,gname3,motive,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,propcomment,summary,suicide,multiple
0,1970,Jul,2,Dominican Republic,Central America & Caribbean,Unknown,Santo Domingo,18.456792,-69.951164,Assassination,Unknown,Unknown Explosive Type,Private Citizens & Property,Named Civilian,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,MANO-D,Unknown,Unknown,Unknown,1.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
1,1970,Unknown,0,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),Unknown,Unknown Explosive Type,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,23rd of September Communist League,Unknown,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0

In [18]:
df1 = df1.drop(["iday","gname2","gname3","nkillus","nwoundus"],axis=1)

In [19]:
print(df1.shape)
df1.head(2)

(181691, 30)

,year,month,country,region,provstate,city,latitude,longitude,attacktype,weaptype,weapsubtype,targtype,targsubtype,targtype2_txt,targsubtype2_txt,targtype3_txt,targsubtype3_txt,group_name,motive,nkill,nkillter,nwound,nwoundte,property,propextent,propvalue,propcomment,summary,suicide,multiple
0,1970,Jul,Dominican Republic,Central America & Caribbean,Unknown,Santo Domingo,18.456792,-69.951164,Assassination,Unknown,Unknown Explosive Type,Private Citizens & Property,Named Civilian,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,MANO-D,Unknown,1.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
1,1970,Unknown,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),Unknown,Unknown Explosive Type,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,23rd of September Communist League,Unknown,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0

In [20]:
# print(df["attacktype2_txt"].unique())
# print()
# print(df["attacktype"].unique())

In [77]:
# print(df["gname2"].value_counts().unique())
# print(df["gname2"].unique())
# print()
# print(df["gname2"].value_counts())
# print()
# print(df["group_name"].value_counts())

In [21]:
# print(df["weaptype1"].unique())
# print()
# print(df["weapsubtype1"].unique())
# print()
# #print(df["weaptype3_txt"].unique())
# print()
# print(df["weapsubtype3_txt"].unique())
# print()
# print(df["weaptype4_txt"].unique())
# print()
# print(df["weapsubtype4_txt"].unique())
# print()

In [22]:
# df["motive"].unique()
# df["motive"].value_counts()

In [23]:
# print(df["targtype1"].unique())
# print()
# print(df["targtype2_txt"].unique())
# print()
# print(df["targtype3_txt"].unique())
# print()
# print("**************************************")
# print(df["targsubtype1"].unique())
# print()
# print(df["targsubtype2_txt"].unique())
# print()
# print(df["targsubtype3_txt"].unique())
# print()

#df = df.drop(["targtype2_txt","targtype3_txt","targsubtype2_txt","targsubtype3_txt"],axis=1)

In [24]:
# print(df["weaptype1"].unique())
# print()
# print(df["weaptype4_txt"].unique())
# print()
# print("**************************************")
# print(df["weapsubtype1"].unique())
# print()
# print(df["weapsubtype3_txt"].unique())
# print()

# print(df["weapsubtype4_txt"].unique())
# print()

# df = df.drop(["weapsubtype3_txt","weapsubtype4_txt"],axis = 1)

In [92]:
import numpy as np

In [25]:
# comm = np.intersect1d(df["weapsubtype1"],df["weapsubtype3_txt"])
# print(comm)

(181691, 31)

In [117]:
# comm = np.intersect1d(df["group_name"],df["gname2"])
# print(comm)
# print()
# print()
# cc = np.intersect1d(comm,df["gname3"])
# cc

In [26]:
# print(df["property"].unique())
# print(df["propextent"].unique())
# #print(df["propvalue"].unique())
# print(df["propcomment"].unique())
# print(df["propcomment"].value_counts())
# print(df["summary"].value_counts())

In [160]:
c = np.intersect1d(df.columns,df1.columns)
# c

array(['city', 'country', 'gname2', 'gname3', 'iday', 'latitude',
       'longitude', 'motive', 'multiple', 'nkill', 'nkillter', 'nkillus',
       'nwound', 'nwoundte', 'nwoundus', 'propcomment', 'property',
       'propextent', 'propvalue', 'provstate', 'region', 'suicide',
       'summary', 'targsubtype2_txt', 'targsubtype3_txt', 'targtype2_txt',
       'targtype3_txt'], dtype=object)

In [27]:
df1.sample(2)

,year,month,country,region,provstate,city,latitude,longitude,attacktype,weaptype,weapsubtype,targtype,targsubtype,targtype2_txt,targsubtype2_txt,targtype3_txt,targsubtype3_txt,group_name,motive,nkill,nkillter,nwound,nwoundte,property,propextent,propvalue,propcomment,summary,suicide,multiple
12167,1980,Oct,Zimbabwe,Sub-Saharan Africa,Salisbury,Salisbury,-17.981844,31.066680,Bombing/Explosion,Explosives,Grenade,Military,Military Unit/Patrol/Convoy,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Unknown,Unknown,0.0,0.0,1.0,0.0,1,4.0,0.0,Unknown,Unknown,0,0.0
107018,2012,Apr,Afghanistan,South Asia,Kandahar,Dooab,31.547778,65.454167,Bombing/Explosion,Explosives,Unknown Explosive Type,Military,NATO,Private Citizens & Property,Unnamed Civilian/Unspecified,Private Citizens & Property,Unnamed Civilian/Unspecified,Taliban,Unknown,0.0,0.0,0.0,0.0,1,4.0,-99.0,A military vehicle was damaged in this attack.,04/14/2012: An explosive device detonated near...,0,1.0

In [28]:
c1 = np.intersect1d(df1["targsubtype2_txt"],df1["targsubtype"])
print(c1)

c2 = np.intersect1d(df1["targtype"],df1["targtype2_txt"])
c2

['Affiliated Institution' 'Aircraft (not at an airport)'
 'Airline Officer/Personnel' 'Airport' 'Alleged Informant' 'Ambulance'
 'Bank/Commerce' 'Bridge/Car Tunnel' 'Bus (excluding tourists)'
 'Bus Station/Stop' 'Civilian Maritime' 'Clinics' 'Commercial Maritime'
 'Construction' 'Diplomatic Personnel (outside of embassy, consulate)'
 'Domestic NGO' 'Election-related' 'Electricity' 'Embassy/Consulate'
 'Entertainment/Cultural/Stadium/Casino' 'Farm/Ranch' 'Farmer'
 'Fire Fighter/Truck' 'Food Supply' 'Gas' 'Gas/Oil/Electric'
 'Government Building/Facility/Office'
 'Government Personnel (excluding police, military)' 'Head of State'
 'Highway/Road/Toll/Traffic Signal' 'Hotel/Resort'
 'House/Apartment/Residence' 'Industrial/Textiles/Factory' 'Intelligence'
 'International NGO'
 'International Organization (peacekeeper, aid agency, compound)'
 'Judge/Attorney/Court' 'Labor Union Related'
 'Laborer (General)/Occupation Identified' 'Legal Services'
 'Marketplace/Plaza/Square' 'Medical/Pharmaceutical'
 'Memorial/Cemetery/Monument' 'Military Aircraft'
 'Military Barracks/Base/Headquarters/Checkpost' 'Military Checkpoint'
 'Military Personnel (soldiers, troops, officers, forces)'
 'Military Recruiting Station/Academy'
 'Military Transportation/Vehicle (excluding convoys)'
 'Military Unit/Patrol/Convoy' 'Military Weaponry' 'Mining'
 'Multinational Corporation' 'Multiple Telecommunication Targets'
 'Museum/Cultural Center/Cultural House' 'NATO' 'Named Civilian'
 'Newspaper Journalist/Staff/Facility' 'Non-State Militia'
 'Non-combatant Personnel' 'Oil' 'Oil Tanker'
 'Other (including online news agencies)' 'Other Facility'
 'Other Personnel' 'Paramilitary' 'Party Office/Facility'
 'Party Official/Candidate/Other Personnel' 'Place of Worship'
 'Police Building (headquarters, station, school)' 'Police Checkpoint'
 'Police Patrol (including vehicles and convoys)'
 'Police Security Forces/Officers' 'Political Party Member/Rally'
 'Politician or Political Party Movement/Meeting/Rally' 'Port'
 'Prison/Jail' 'Private Security Company/Firm'
 'Procession/Gathering (funeral, wedding, birthday, religious)'
 'Protester'
 'Public Area (garden, parking lot, garage, beach, public building, camp)'
 'Race/Ethnicity Identified' 'Radio' 'Radio Journalist/Staff/Facility'
 'Rally' 'Refugee (including Camps/IDP/Asylum Seekers)'
 'Religion Identified' 'Religious Figure' 'Restaurant/Bar/Café'
 'Retail/Grocery/Bakery' 'School/University/Educational Building'
 'Student' 'Subway' 'Taxi/Rickshaw' 'Teacher/Professor/Instructor'
 'Telephone/Telegraph' 'Television' 'Television Journalist/Staff/Facility'
 'Terrorist' 'Tour Bus/Van' 'Tourism Travel Agency' 'Tourist'
 'Train/Train Tracks/Trolley' 'Unnamed Civilian/Unspecified'
 'Vehicles/Transportation' 'Village/City/Town/Suburb' 'Water Supply']

array(['Abortion Related', 'Airports & Aircraft', 'Business',
       'Educational Institution', 'Food or Water Supply',
       'Government (Diplomatic)', 'Government (General)',
       'Journalists & Media', 'Maritime', 'Military', 'NGO', 'Other',
       'Police', 'Private Citizens & Property',
       'Religious Figures/Institutions', 'Telecommunication',
       'Terrorists/Non-State Militia', 'Tourists', 'Transportation',
       'Unknown', 'Utilities', 'Violent Political Party'], dtype=object)

In [29]:
df1["targtype2_txt"].unique()

array(['Private Citizens & Property', 'Police', 'Educational Institution',
       'Unknown', 'Business', 'Government (General)',
       'Government (Diplomatic)', 'Telecommunication', 'Utilities',
       'Airports & Aircraft', 'Military',
       'Religious Figures/Institutions', 'Terrorists/Non-State Militia',
       'Transportation', 'Journalists & Media', 'Tourists',
       'Violent Political Party', 'NGO', 'Maritime', 'Abortion Related',
       'Other', 'Food or Water Supply'], dtype=object)

In [30]:
df1 = df1.drop(["targsubtype2_txt","targsubtype3_txt","targtype2_txt","targtype3_txt"],axis=1)

In [31]:

df1.shape

(181691, 26)

In [32]:
df1.head(2)

,year,month,country,region,provstate,city,latitude,longitude,attacktype,weaptype,weapsubtype,targtype,targsubtype,group_name,motive,nkill,nkillter,nwound,nwoundte,property,propextent,propvalue,propcomment,summary,suicide,multiple
0,1970,Jul,Dominican Republic,Central America & Caribbean,Unknown,Santo Domingo,18.456792,-69.951164,Assassination,Unknown,Unknown Explosive Type,Private Citizens & Property,Named Civilian,MANO-D,Unknown,1.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0
1,1970,Unknown,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),Unknown,Unknown Explosive Type,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",23rd of September Communist League,Unknown,0.0,0.0,0.0,0.0,0,Unknown,0.0,Unknown,Unknown,0,0.0

In [33]:
df1["casualites"] = df1["nkill"]+df1["nwound"]

In [34]:
df1["nkill"].unique().dtype

dtype('float64')

In [36]:
df1 = df1.astype({"nkill":"int64","nwound":"int64","propvalue":"int64","casualites":"int64"})

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 27 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   year         181691 non-null  int64
 1   month        181691 non-null  object
 2   country      181691 non-null  object
 3   region       181691 non-null  object
 4   provstate    181691 non-null  object
 5   city         181691 non-null  object
 6   latitude     181691 non-null  float64
 7   longitude    181691 non-null  float64
 8   attacktype   181691 non-null  object
 9   weaptype     181691 non-null  object
 10  weapsubtype  181691 non-null  object
 11  targtype     181691 non-null  object
 12  targsubtype  181691 non-null  object
 13  group_name   181691 non-null  object
 14  motive       181691 non-null  object
 15  nkill        181691 non-null  int64
 16  nkillter     181691 non-null  float64
 17  nwound       181691 non-null  int64
 18  nwoundte     181691 non-null  float64
 19  property     181691 non-null  int64
 20  propextent   181691 non-null  object
 21  propvalue    181691 non-null  int64
 22  propcomment  181691 non-null  object
 23  summary      181691 non-null  object
 24  suicide      181691 non-null  int64
 25  multiple     181691 non-null  object
 26  casualites   181691 non-null  int64
dtypes: float64(4), int64(7), object(16)
memory usage: 37.4+ MB

In [38]:
df1["casualites"].unique()

array([   1,    0,    2,    7,   16,   47,   17,    5,    3,   36,   10,
         12,   13,   20,    4,    6,    8,   24,   27,   25,   15,   26,
         14,  132,   56,    9,   98,   81,   28,  239,   60,   23,   80,
         31,   34,   21,   95,  110,   11,   42,   39,   88,   82,   30,
         92,   91,   57,  127,   18,   22,   46,   33,   19,   68,   85,
         32,   38,   41,   55,   73,   50,  295,   51,  100,   45,  118,
         43,   54,   48,  258,  422,   29,   65,   69,   67,   52,   37,
         35,  141,   94,   44,   90,  111,   86,  140,   49,  106,  273,
        300,   87,  228,   40,   58,   70,   77,  174,   74,   72,   59,
        113,   63,  383,  225,  166,   75,   61,  135,  158,   64,  120,
        760,  114,  124,   76,   71,   62,  183,  102,   78,  236,  396,
         66,  168,  200,  180,  316,  176,  116,  270,   53,  136,  250,
        318,   93,  751,  400,   79,  130,  112,  325,  246,  260,  175,
        329,  150,   96,  134,   97,   83,  240,  160,  233,  101,  125,
        227,  173,  170,  104,  232,  109,  190,  401,  375,  458,  159,
        138,  145,  177,  119,  182,  171,  107,  285,  128,  187,   89,
        185,  121,  198,   99,  142,   84,  137,  115,  500,  800,  148,
        226, 1180,  507,  321,  156,  354,  217, 5513,  818,  671,  229,
        172,  126,  108, 1362,  242,  405,  404,  452,  154,  186,  123,
        275,  139,  450,  199,  152,  498,  206,  320,  297,  105, 4224,
        249,  103,  164,  201,  149,  131,  129,  161,  122,  146,  419,
       9574,  296,  181,  251,  317,  178,  194,  256,  202,  162,  184,
        221,  343,  487,  523,  469,  512,  734,  280, 1071,  192,  191,
        210,  155,  144,  179,  367,  702,  167,  312, 1005,  157,  211,
        253,  245,  462,  151,  209,  188,  248,  207,  366,  216,  292,
        315,  204,  247,  279,  214,  263, 1000,  391,  220, 1161,  212,
        261,  272,  215,  165,  193,  230,  294,  654,  143,  436,  437,
        147,  133,  255,  219,  331,  163,  222,  268,  414,  427,  397,
        196,  330,  218,  442,  283,  195,  687,  670, 1570,  310,  298,
        953,  517,  392,  117,  153,  416,  536,  350,  224, 1503,  430,
        418,  649,  583,  520,  313,  274,  284,  433,  197,  584,  910,
        904,  438], dtype=int64)

In [41]:
df1.to_csv(r"C:\Users\ujjwa\OneDrive\Desktop\DBDA-PROJECT\GTD_clean_data.csv",index=False)

In [43]:
pip install pandas sqlalchemy mysql-connector-python

Requirement already satisfied: pandas in c:\users\ujjwa\anaconda3\lib\site-packages (1.4.4)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: sqlalchemy in c:\users\ujjwa\anaconda3\lib\site-packages (1.4.39)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp39-cp39-win_amd64.whl (14.3 MB)
     ---------------------------------------- 14.3/14.3 MB 1.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.18.5 in c:\users\ujjwa\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\ujjwa\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\ujjwa\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ujjwa\anaconda3\lib\site-packages (from sqlalchemy) (1.1.1)
Requirement already satisfied: six>=1.5 in c:\users\ujjwa\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [50]:
import pandas as pd
from sqlalchemy import create_engine

# Define your database connection parameters
user = 'root'
password = 'Ujjwal@123'
host = 'localhost'  # or your MySQL server IP
database = 'ujjwal'

# Create a connection string
connection_string = f'mysql+mysqlconnector://{user}:{password}@{host}/{database}'
engine = create_engine(connection_string)

# Load the CSV file into a DataFrame
df = pd.read_csv(r'C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/GTD_clean_data.csv')

# Write the DataFrame to a MySQL table
# If the table does not exist, it will be created automatically
df.to_sql(name='GTD', con=engine, index=False, if_exists='replace')

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_26740\597848978.py:15: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/GTD_clean_data.csv')

DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '123@localhost' (11003)
(Background on this error at: https://sqlalche.me/e/14/4xp6)

In [55]:
import pandas as pd
from sqlalchemy import create_engine

# Define your database connection parameters
user = 'root'
password = 'Ujjwal@123'
host = 'localhost'  # or your MySQL server IP
database = 'ujjwal'
port = "3306"
# Create a connection string
connection_string = f'mysql+mysqlconnector://{user}:{password}@{host}/{database}'
engine = create_engine(connection_string)

# Load the CSV file into a DataFrame
csv_file_path = r'C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/GTD_clean_data.csv'
df = pd.read_csv(csv_file_path)

# Example: Show the first few rows of the DataFrame
print(df.head())
df.to_sql(name='GTD', con=engine, index=False, if_exists='replace')

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_26740\1030950574.py:16: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file_path)

   year    month             country                       region provstate  \
0  1970      Jul  Dominican Republic  Central America & Caribbean   Unknown
1  1970  Unknown              Mexico                North America   Federal
2  1970      Jan         Philippines               Southeast Asia    Tarlac
3  1970      Jan              Greece               Western Europe    Attica
4  1970      Jan               Japan                    East Asia   Fukouka

            city   latitude   longitude                      attacktype  \
0  Santo Domingo  18.456792  -69.951164                   Assassination
1    Mexico city  19.371887  -99.086624     Hostage Taking (Kidnapping)
2        Unknown  15.478598  120.599741                   Assassination
3         Athens  37.997490   23.762728               Bombing/Explosion
4        Fukouka  33.580412  130.396361  Facility/Infrastructure Attack

     weaptype             weapsubtype                     targtype  \
0     Unknown  Unknown Explosive Type  Private Citizens & Property
1     Unknown  Unknown Explosive Type      Government (Diplomatic)
2     Unknown  Unknown Explosive Type          Journalists & Media
3  Explosives  Unknown Explosive Type      Government (Diplomatic)
4  Incendiary  Unknown Explosive Type      Government (Diplomatic)

                                         targsubtype  \
0                                     Named Civilian
1  Diplomatic Personnel (outside of embassy, cons...
2                    Radio Journalist/Staff/Facility
3                                  Embassy/Consulate
4                                  Embassy/Consulate

                           group_name   motive  nkill  nkillter  nwound  \
0                              MANO-D  Unknown      1       0.0       0
1  23rd of September Communist League  Unknown      0       0.0       0
2                             Unknown  Unknown      1       0.0       0
3                             Unknown  Unknown      0       0.0       0
4                             Unknown  Unknown      0       0.0       0

   nwoundte  property propextent  propvalue propcomment  summary  suicide  \
0       0.0         0    Unknown          0     Unknown  Unknown        0
1       0.0         0    Unknown          0     Unknown  Unknown        0
2       0.0         0    Unknown          0     Unknown  Unknown        0
3       0.0         1    Unknown          0     Unknown  Unknown        0
4       0.0         1    Unknown          0     Unknown  Unknown        0

  multiple  casualites
0      0.0           1
1      0.0           0
2      0.0           1
3      0.0           0
4      0.0           0

DatabaseError: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '123@123@localhost' (11003)
(Background on this error at: https://sqlalche.me/e/14/4xp6)

In [9]:
import pandas as pd
from sqlalchemy import*

# Define your database connection parameters
user = 'root'
password = 'Ujjwal@123'
host = '127.0.0.1'  # Ensure this is correctly set
database = 'ujjwal'
port = "3306"
# Create a connection string
connection_string = f'mysql+mysqlconnector://{user}:{password}@{host}/{database}'
engine = create_engine(connection_string)

# Load the CSV file into a DataFrame
csv_file_path = r'C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/GTD_clean_data.csv'
df = pd.read_csv(csv_file_path)

# Example: Print the first few rows of the DataFrame
print(df.head())

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_26748\4185330225.py:16: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file_path)

   year    month             country                       region provstate  \
0  1970      Jul  Dominican Republic  Central America & Caribbean   Unknown
1  1970  Unknown              Mexico                North America   Federal
2  1970      Jan         Philippines               Southeast Asia    Tarlac
3  1970      Jan              Greece               Western Europe    Attica
4  1970      Jan               Japan                    East Asia   Fukouka

            city   latitude   longitude                      attacktype  \
0  Santo Domingo  18.456792  -69.951164                   Assassination
1    Mexico city  19.371887  -99.086624     Hostage Taking (Kidnapping)
2        Unknown  15.478598  120.599741                   Assassination
3         Athens  37.997490   23.762728               Bombing/Explosion
4        Fukouka  33.580412  130.396361  Facility/Infrastructure Attack

     weaptype  ... nwound nwoundte property propextent propvalue  propcomment  \
0     Unknown  ...      0      0.0        0    Unknown         0      Unknown
1     Unknown  ...      0      0.0        0    Unknown         0      Unknown
2     Unknown  ...      0      0.0        0    Unknown         0      Unknown
3  Explosives  ...      0      0.0        1    Unknown         0      Unknown
4  Incendiary  ...      0      0.0        1    Unknown         0      Unknown

   summary  suicide  multiple  casualites
0  Unknown        0       0.0           1
1  Unknown        0       0.0           0
2  Unknown        0       0.0           1
3  Unknown        0       0.0           0
4  Unknown        0       0.0           0

[5 rows x 27 columns]

In [10]:
import mysql.connector

try:
    connection = mysql.connector.connect(
        host='localhost',
        user='root',
        password='Ujjwal@123',
        database='ujjwal'
    )
    if connection.is_connected():
        print("Connected to MySQL database")
except mysql.connector.Error as err:
    print(f"Error: {err}")
finally:
    if connection.is_connected():
        connection.close()

Connected to MySQL database

In [14]:
# df.to_sql(name='GTD', con=engine, index=False, if_exists='replace')

In [13]:
df.columns

Index(['year', 'month', 'country', 'region', 'provstate', 'city', 'latitude',
       'longitude', 'attacktype', 'weaptype', 'weapsubtype', 'targtype',
       'targsubtype', 'group_name', 'motive', 'nkill', 'nkillter', 'nwound',
       'nwoundte', 'property', 'propextent', 'propvalue', 'propcomment',
       'summary', 'suicide', 'multiple', 'casualites'],
      dtype='object')

In [16]:
try:
    # Load the CSV file into a DataFrame
    df = pd.read_csv(r'C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/GTD_clean_data.csv')  # Replace with your CSV file path

    # Write the DataFrame to the MySQL table
    df.to_sql(name='gtd', con=engine, index=False, if_exists='append')
    print("Data loaded successfully.")

except Exception as e:
    print(f"An error occurred: {e}")

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_26748\1340434440.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:/Users/ujjwa/OneDrive/Desktop/DBDA-PROJECT/GTD_clean_data.csv')  # Replace with your CSV file path

An error occurred: (mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host '123@127.0.0.1' (11003)
(Background on this error at: https://sqlalche.me/e/14/4xp6)

In [18]:
df["nkill"].unique()

array([   1,    0,    7,   47,    2,   36,    5,    3,    4,   25,   15,
         26,    8,   81,    6,    9,   16,   30,   31,   12,   21,   14,
         88,   11,   10,   27,   18,   22,   19,   92,   13,   73,  100,
         42,   43,   17,   98,  422,   48,   34,   54,   50,   35,   20,
         41,   37,   28,   40,   32,   85,   23,  300,   60,   24,   58,
         70,   87,   45,   38,   29,   74,   83,   90,   66,   80,   67,
         51,   39,  114,  124,   76,   33,   75,   57,   62,   46,   56,
         63,  120,  102,   78,   79,   52,   77,  200,   49,  111,  165,
         44,  241,   64,  108,   65,  132,  270,  228,  110,  136,  180,
        250,   93,  130,   59,   94,   53,  146,  329,   97,   71,  240,
        227,  126,  106,  388,   68,   84,   82,  171,  107,   55,  112,
         72,   96,  140,   61,  105,  150,  115,   89, 1180,  170,  168,
        121,  375,   91,  304,  123,  135,  256,  109,  271,  206,  104,
        320,  275,  224,  118,  129,   95,  259, 1384, 1383,  190,  119,
        101,  116,  518,  344,  160,  188,  103,  205,  145,  153,  127,
         69,  141,  134,  400,   86,  184,  210,  142,  212,  287,  315,
        151,  670, 1570,  310,  298,  953,  517,  201,  122,  158,  117,
        144,  208,  152,  230,  280,  174,  143,  383,  283,  154,  284,
        433,  266,  133,  163,  128,  588,  311], dtype=int64)

In [20]:
df["nwound"].unique()

array([   0,    1,    2,    7,    9,   17,    5,    3,   10,   12,   20,
          4,   11,   27,   13,   19,  130,   56,   24,    6,   72,  238,
         55,   15,    8,   18,   50,   34,   14,   70,  102,   41,   48,
         36,   25,   81,   54,   53,  100,   45,   33,   40,   62,   74,
         22,   31,   16,   30,  285,   23,   42,   43,   76,   44,   52,
         46,   49,  160,   37,   21,   60,   78,   26,   28,   39,   38,
         35,   32,   80,   47,  188,  215,   85,   75,  161,   90,  300,
         95,  135,   61,  138,   71,  700,   66,  136,  120,  217,  319,
        133,   68,   73,   29,  751,  200,  112,  250,   82,  132,  230,
        107,  114,   84,  140,  150,   96,   51,   58,   64,  295,  106,
        125,   69,   59,   57,  122,  109,   88,  115,  176,  220,   97,
         65,  800,  173,   92,  500,  236,   98,  286,  141, 5500,  650,
        671,   86,  104,   83,  101, 1272,  105,  386,  391,  110,  149,
         89,   91,  119,   77,  118,   67,  170,  194,  192,  227,  260,
       4000,  180,  184,   99,   94,  137, 8190, 8191,  171,  121,  103,
        162,  197,  151,  224,  134,  233,  167,  450,  216,  145,   63,
        727,  182,  159,  108,  128,  340,  163,  542,   87,  155,  817,
        257,  148,  123,  246,  127,  347,  178,  168,  207,  183,  117,
        750,  147, 1001,   93,  154,  235,  158,  211,  116,  276,  552,
        360,  113,  157,  175,  301,  131,  400,  370,  169,  201,  111,
        143,  153,  124,   79,  270,  152,  296,  245, 1500,  351,  600,
        433,  177,  491,  405,  851,  316], dtype=int64)

In [1]:
df.shape

NameError: name 'df' is not defined